

# Site settings
title: Alkeymia
description: "Cours en ligne"
url: "https://grader-pig-68500.netlify.com" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
permalink: :title/

timezone: Europe/Paris
mainColor: '#000000'
cover: "/assets/cover.png"
logo: "/assets/logo.png"

incremental: true
profile: true

 # seo-tag
author: alkeymia
twitter:
  username: AlkeymiaEng
social:
  type: personn
  name: alkeymia
  links:
    - https://twitter.com/AlkeymiaEng
    - https://linkedin.com/alkeymia

# Build settings
markdown: kramdown
kramdown:
  input: GFM

feed:
  path: feed

sass:
  sass_dir: _sass
  style: compressed

collections:
  formations:
    output: true
    order: date asc
    permalink: formations/:title
  sessions:
    output: true
    order: date asc
    permalink: sessions/:title
    sitemap: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
  - scope:
      path: "en"
      type: pages
    values:
      lang: en
  - scope:
      path: "fr"
      type: pages
    values:
      lang: fr
  - scope:
      path: "_posts/en"
      type: posts
    values:
      lang: en
      permalink: en/:year/:month/:day/:title/
  - scope:
      path: "_posts/fr"
      type: posts
    values:
      lang: fr
      permalink: fr/:year/:month/:day/:title/
  - scope:
      path: "_formations"
      type: "formations"
    values:
      layout: formations
  - scope:
      path: "_formations/fr"
      type: "formations"
    values:
      lang: "fr"
      permalink: fr/:collection/:title/
  - scope:
      path: "_formations/en"
      type: "formations"
    values:
      lang: "en"
      permalink: en/:collection/:title/
  - scope:
      path: "_sessions"
      type: "sessions"
    values:
      layout: sessions
  - scope:
      path: "_sessions/fr"
      type: "sessions"
    values:
      lang: "fr"
      permalink: fr/:collection/:title/
  - scope:
      path: "_sessions/en"
      type: "sessions"
    values:
      lang: "en"
      permalink: en/:collection/:title/

# # Plugin: generate pages from Yaml
# page_gen-dirs: true # uncomment, if you prefer to generate named folders
# page_gen:
#   - data: 'formations'
#     template: 'subscribe'
#     name: 'teacher'
#     lang: 'lang'
#     theme: 'theme'
#     dir: 'contacts'

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Plugin :: see gemfle file
plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-default-layout

# File not to compile
exclude:
  - .cache
  - .editorconfig
  - .gitattributes
  - .gitignore
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

# File to keep
keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"
